# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# **Taller Limpieza y transformación de datos**🧹

**IMPORTANTE**: Guarda una copia de este notebook en tu Google Drive o computador.

**Taller en grupos de 3 o parejas.**

**Nombres estudiantes:**

-
-
-

**Forma de entrega:**

- Nombrar el archivo de la siguiente forma:“Taller_Limpieza_nombres_y_appellidos.ipynb”.
- Suba el Jupyter Notebook a su cuenta en Github y envíe el link en el siguiente Forms: https://forms.office.com/r/6GZ89uiLNC.

**IMPORTANTE:** No se recibirán talleres en Google Colab, el notebook debe estar subido en Github.

**Plazo de entrega:**

19 de marzo de 2026, máximo a las 11:59 p.m. Tenga en cuenta que luego de esa hora el formulario en forms se cierra. El Jupupyter Notebook también debe quedar subido en Github antes de esa hora.

**Instrucciones Generales:**

Completa el código en las celdas marcadas con `### TU CÓDIGO AQUÍ ###`. Puedes añadir más celdas si lo requieres.

Utilice la base de la GEIH de julio a diciembre de 2025, la cual se encuentra en https://drive.google.com/drive/folders/1Th4TWdsOahAAvBUKxixFhaELC_KPsl3y?usp=sharing. Tenga en cuenta sep="," y encoding='latin1'. Las variables 'DPTO' y 'RAMA4D_R4' deben ser cargadas como string.

# Ejercicio 1: Importar librerías y cargar datos

1.	Importe todas las librerías que vaya a utilizar.

In [1]:
import pandas as pd
import numpy as np
import os

2.	Mejore la visualización de los dataframes como se ha visto en clase.

In [2]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

3.	Conéctese a su Google Drive y establezca la ruta del dataset.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
path = '/content/drive/MyDrive/bases ia/GEIH_2025_Jul_Dic_Consolidado.csv'

4.	Cargue los datos en el notebook. Llame al dataframe 'df_geih'

In [11]:
df=  pd.read_csv(path, sep=",", encoding='latin1', dtype={'DPTO': str, 'RAMA4D_R4': str})
df

/tmp/ipykernel_1231/880271008.py:1: DtypeWarning: Columns (74,89,102,110,116,137,204,254,257,261,263,266,268,277,298,306) have mixed types. Specify dtype option on import or set low_memory=False.
  df=  pd.read_csv(path, sep=",", encoding='latin1', dtype={'DPTO': str, 'RAMA4D_R4': str})

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S10,P5222S11,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P6008,P70,FFT,FT,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S7A1,P3362S8,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,PET,INGLABO,OCI,OFICIO_C8,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P1805,P1879,P1880,P1880S1,P1881,P1881S1,P1882,P3044S2,P3045S1,P3045S2,P3045S3,P3046,P3047,P3048,P3049,P3051,P3052,P3053,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P3068,P3069,P3071S3,P3072S2,P3073,P3363,P3364,P3364S1,P3365,P3365S1,P514,P515,P550,P6400,P6410,P6420S2,P6422,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P6440,P6450,P6460,P6460S1,P6500,P6510,P6510S1,P6510S2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P6750,P6760,P6765,P6765S1,P6775,P6780,P6780S1,P6790,P6800,P6810,P6810S1,P6830,P6830S1,P6850,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P7020,P7026,P7028,P7028S1,P7040,P7045,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P7240,P7240S1,P760,P9440,P9450,RAMA2D_R4,RAMA4D_R4,DESCRIPCION_CIIU,NOMBRE_DPTO
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,27.75,08,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,1,5,1,1,1.00,2,2,2,NaN,2,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"790,000.00",1.00,"9,212.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,3.00,NaN,10.00,143.00,2.00,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,1.00,2.00,NaN,NaN,NaN,1.00,1.00,NaN,1.00,NaN,NaN,1.00,2.00,2.00,2.00,2.00,84.00,7.00,NaN,1.00,1.00,NaN,NaN,"590,000.00",2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,NaN,NaN,40.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,1.00,3.00,4.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,3.00,NaN,0.00,2.00,2.00,1.00,0143,Cría de ovejas y cabras,ATLÁNTICO
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,27.75,08,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,1,5,1,1,1.00,2,2,2,NaN,2,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2,1,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,59.11,08,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,1,2,1,1,1.00,2,2,2,NaN,2,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"1,100,000.00",1.00,"1,311.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00,NaN,3.00,NaN,4.00,141.00,2.00,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,1.00,2.00,NaN,NaN,NaN,1.00,1.00,NaN,1.00,NaN,NaN,1.00,2.00,2.00,2.00,2.00,48.00,1.00,NaN,1.00,1.00,NaN,NaN,"1,000,000.00",2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,NaN,NaN,70.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,1.00,36.00,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,8.00,NaN,1.00,2.00,2.00,1.00,0141,Cría de ganado bovino y bufalino,ATLÁNTICO
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,59.11,08,1,2,2,50,2.00,"1,975.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,1,2,1,1,1.00,2,2,2,NaN,2,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4,1,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,1.00,9.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,59.11,08,1,3,1,19,6.00,"2,006.00",3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,1,2,1,1,1.00,2,2,2,NaN,2,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"820,000.00",1.00,"9,212.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.00,NaN,3.00,NaN,3.00,141.00,2.00,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,1.00,2.00,NaN,NaN,NaN,1.00,1.00,NaN,1.00,NaN,NaN,1.00,2.00,2.00,2.00,2.00,48.00,7.00,NaN,1.00,1.00,NaN,NaN,"720,000.00",2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,NaN,NaN,60.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,1.00,18.00,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,3.00,NaN,1.00,2.00,2.00,1.00,0141,Cría de ganado bovino y bufalino,ATLÁNTICO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,20251252,12,2025,8473907,1,1,1,10,NaN,2,378.31,73,1,1,2,61,6.00,"1,964.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,3.00,2.00,NaN,1,1.00,5.00,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,3.00,3.00,NaN,NaN,NaN,1.00,2.00,1.00,1,1,4,1,2.00,2,2,2,NaN,1,4,1,2,1.00,4,1,1,4.00,4,NaN,NaN,NaN,"600,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"1,400,000.00",1.00,"9,111.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,14.00,NaN,NaN,"9,700.00",2.00,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,1.00,2.00,NaN,NaN,NaN,1.00,1.00,NaN,1.00,NaN,NaN,2.00,2.00,2.00,2.00,2.00,1.00,3.00,NaN,1.00,1.00,NaN,NaN,"800,000.00",2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"600,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,48.00,NaN,NaN,NaN,NaN,48.00,1.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,2.00,1.00,0.00,4.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,3.00,NaN,72.00,2.00,2.00,97.00,9700,Actividades de los hogares individuales como e...,TOLIMA
409123,20251252,12,2025,8473908,1,1,1,10,54.00,1,534.55,54,1,1,1,58,3.00,"1,967.00",1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,2.00,1.00,"120,000.00",4,4,4,4,4,4,4,4,1.00,1.00,2.00,13.00,9.00,111.00,9.00,111.00,2.00,1.00,1.00,2,1,4,1,2.00,1,1,1,3.00,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,"300,000,000.00","700,000.00",NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,4,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.00,VACACIONES,NaN,2.00,1.00,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"3,000,000.00",1.00,"2,330.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.00,NaN,8.00,NaN,30.00,"8,530.00",2.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,5.00,2.00,NaN,NaN,NaN,1.00,1.00,NaN,2.00,4.00,"8,413.00",1.00,1.00,1.00,1.00,1.00,60.00,2.00,NaN,1.00,2.00,1.00,NaN,"3,000,000.00",2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,1.00,"1,500,000.00",1.00,"3,000,000.00",1.00,"1,500,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,30.00,2.00,NaN,3.00,NaN,0.00,7.00,NaN,1.00,NaN,1.00,3.00,1.00,20.00,1.00,1.00,48.00,4.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,2.00,NaN,0.00,2.00,1.00,85.00,8530,Establecimientos que combinan diferentes nivel...,NORTE DE SANTANDER
409124,20251252,12,2025,8473908,1,2,1,10,54.00,1,534.55,54,1,2,2,51,3.00,"1,974.00",2,2,NaN,2,NaN,2,1.00,2,6,NaN,NaN,3.00,1.00,1.00,1,1.00,1.00,"318,240.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,12.00,4.00,413.00,9.00,413.00,1.00,2.00,1.00,2,1,4,1,2.00,1,1,1,3.00,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,"300,000,000.00","700,000.00",NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,4,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"7,956,000.00",1.00,"2,411.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,2.00,NaN,60.00,"8,412.00",2.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,1.00,1.00,"79,600.00",NaN,NaN,1.00,1.00,NaN,1.00,NaN,NaN,1.00,1.00,1.00,1.00,1.00,23.00,2.00,NaN,1.00,2.00,2.00,24.00,"7,956,000.00",2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,1.00,"3,500,000.00",1.00,"7,956,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,44.00,NaN,NaN,NaN,NaN,44.00,7.00,NaN,1.00,NaN,1.00,2.00,1.00,10.00,1.00,1.00,48.00,4.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,2.00,NaN,4.00,2.00,1.00,84.00,8412,Actividades ejecutivas de la administración pú...,NORTE DE SANTANDER
409125,20251252,12,2025,8473908,1,3,1,10,54.00,1,534.55,54,1,3,2,31,2.00,"1,994.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,1.00,3.00,"178,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,719.00,7.00,719.00,1.00,2.00,1.00,2,1,4,1,2.00,1,1,1,3.00,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,"300,000,000.00","700,000.00",NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,4,1,NaN,1.00,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NORTE DE SANTANDER
409126,20251252,12,2025,8473908,1,4,1,10,54.00,1,534.55,54,1,4,2,26,2.00,"1,999.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,421.00,7.00,421.00,1.00,2.00,1.00,2,1,4,1,2.00,1,1,1,3.00,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,"300,000,000.00","700,000.00",NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,4,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.00,DESCANSANDO EN SU HOGAR,NaN,2.00,1.00,5.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"500,000.00",1.00,"5,221.00",2.00,NaN,NaN,NaN,NaN,3.00,2.00,1.00,3.00,NaN,14.00,NaN,NaN,"4,791.00",NaN,NaN,NaN,NaN,1.00,1.00,1.00,NaN,"700,000.00",1.00,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,2.00,NaN,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,4.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"500,000.00",NaN,6.00,NaN,NaN,1.00,NaN,10.00,10.00,1.00,NaN,5.00,NaN,0.00,1.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,1.00,6.00,4.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,1.00,44.00,2.00,2.00,1.00,1.00,1.00,1.00,1.00,2.00,2.00,2.00,2.00,2.00,NaN,1.00,1.00,1.00,2.00,1.00,2.00,2.00,NaN,0.00,NaN,2.00,47.00,4791,Comercio al por menor realizado a través de in...,NORTE DE SANTANDER

5. Obtenga las dimensiones de la base

In [13]:
df.shape

(409127, 314)

# Ejercicio 2:  Seleccionar y renombrar columnas

La GEIH contiene cientos de variables. Para nuestro análisis del mercado laboral, nos enfocaremos en un subconjunto.

Adicionalmente, los nombres de las columnas en la GEIH son códigos. Para hacer el análisis más intuitivo, vamos a renombrarlas.

1. Crea un nuevo DataFrame llamado `df_empleo` que contenga únicamente las columnas que están en la lista `columnas_interes`.

In [14]:
columnas_interes = ['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'MES', 'CLASE', 'DPTO', 'FEX_C18', 'PT', 'P3271', 'P6040', 'P6080', 'P3043', 'OCI',
                    'P6430', 'RAMA4D_R4', 'INGLABO', 'DESCRIPCION_CIIU', 'NOMBRE_DPTO']

In [15]:
df_empleo= df[columnas_interes]
df_empleo

,DIRECTORIO,SECUENCIA_P,ORDEN,MES,CLASE,DPTO,FEX_C18,PT,P3271,P6040,P6080,P3043,OCI,P6430,RAMA4D_R4,INGLABO,DESCRIPCION_CIIU,NOMBRE_DPTO
0,8283143,1,1,7,2,08,27.75,1,1,72,6,NaN,1.00,7.00,0143,"790,000.00",Cría de ovejas y cabras,ATLÁNTICO
1,8283143,1,2,7,2,08,27.75,1,2,34,6,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
2,8283145,1,1,7,2,08,59.11,1,1,45,6,NaN,1.00,1.00,0141,"1,100,000.00",Cría de ganado bovino y bufalino,ATLÁNTICO
3,8283145,1,2,7,2,08,59.11,1,2,50,6,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
4,8283145,1,3,7,2,08,59.11,1,1,19,6,NaN,1.00,7.00,0141,"820,000.00",Cría de ganado bovino y bufalino,ATLÁNTICO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,8473907,1,1,12,2,73,378.31,1,2,61,6,NaN,1.00,3.00,9700,"1,400,000.00",Actividades de los hogares individuales como e...,TOLIMA
409123,8473908,1,1,12,1,54,534.55,1,1,58,6,9.00,1.00,2.00,8530,"3,000,000.00",Establecimientos que combinan diferentes nivel...,NORTE DE SANTANDER
409124,8473908,1,2,12,1,54,534.55,1,2,51,6,9.00,1.00,2.00,8412,"7,956,000.00",Actividades ejecutivas de la administración pú...,NORTE DE SANTANDER
409125,8473908,1,3,12,1,54,534.55,1,2,31,6,7.00,NaN,NaN,NaN,NaN,NaN,NORTE DE SANTANDER
409126,8473908,1,4,12,1,54,534.55,1,2,26,6,7.00,1.00,4.00,4791,"500,000.00",Comercio al por menor realizado a través de in...,NORTE DE SANTANDER

2. Renombra las columnas del DataFrame `df_empleo` utilizando el diccionario `mapa_nombres`.

In [17]:
mapa_nombres = {
'DIRECTORIO': 'id_vivienda',
'SECUENCIA_P': 'id_hogar',
'ORDEN': 'id_persona',
'MES': 'mes',
'CLASE': 'clase',
'DPTO': 'departamento',
'FEX_C18': 'factor_expansion',
'PT': 'poblacion_total',
'P3271': 'sexo',
'P6040': 'edad',
'P6080': 'grupo_etnico',
'P3043': 'nivel_educativo',
'OCI': 'ocupados',
'P6430': 'categoria_ocupacional',
'RAMA4D_R4': 'cod_ciiu',
'INGLABO': 'ingreso_laboral',
'DESCRIPCION_CIIU': 'desc_ciiu',
'NOMBRE_DPTO': 'nombre_dpto'}

In [18]:
df_empleo = df_empleo.rename(columns=mapa_nombres)
df_empleo

,id_vivienda,id_hogar,id_persona,mes,clase,departamento,factor_expansion,poblacion_total,sexo,edad,grupo_etnico,nivel_educativo,ocupados,categoria_ocupacional,cod_ciiu,ingreso_laboral,desc_ciiu,nombre_dpto
0,8283143,1,1,7,2,08,27.75,1,1,72,6,NaN,1.00,7.00,0143,"790,000.00",Cría de ovejas y cabras,ATLÁNTICO
1,8283143,1,2,7,2,08,27.75,1,2,34,6,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
2,8283145,1,1,7,2,08,59.11,1,1,45,6,NaN,1.00,1.00,0141,"1,100,000.00",Cría de ganado bovino y bufalino,ATLÁNTICO
3,8283145,1,2,7,2,08,59.11,1,2,50,6,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
4,8283145,1,3,7,2,08,59.11,1,1,19,6,NaN,1.00,7.00,0141,"820,000.00",Cría de ganado bovino y bufalino,ATLÁNTICO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,8473907,1,1,12,2,73,378.31,1,2,61,6,NaN,1.00,3.00,9700,"1,400,000.00",Actividades de los hogares individuales como e...,TOLIMA
409123,8473908,1,1,12,1,54,534.55,1,1,58,6,9.00,1.00,2.00,8530,"3,000,000.00",Establecimientos que combinan diferentes nivel...,NORTE DE SANTANDER
409124,8473908,1,2,12,1,54,534.55,1,2,51,6,9.00,1.00,2.00,8412,"7,956,000.00",Actividades ejecutivas de la administración pú...,NORTE DE SANTANDER
409125,8473908,1,3,12,1,54,534.55,1,2,31,6,7.00,NaN,NaN,NaN,NaN,NaN,NORTE DE SANTANDER
409126,8473908,1,4,12,1,54,534.55,1,2,26,6,7.00,1.00,4.00,4791,"500,000.00",Comercio al por menor realizado a través de in...,NORTE DE SANTANDER

3. Obtenga las dimensiones de la base

In [19]:
df_empleo.shape

(409127, 18)

# Ejercicio 3: Revisión de duplicados

Un paso crucial en la limpieza es asegurar que no haya observaciones duplicadas que puedan sesgar nuestro análisis.

1. Verifica si hay filas duplicadas en `df_empleo`.

In [20]:
df_empleo.duplicated().any()

np.False_

2. Cuenta cuántas filas duplicadas existen.

In [21]:
df_empleo.duplicated().sum()

np.int64(0)

3. Elimina las filas duplicadas, si las hay.

In [ ]:
#N/A

4. Verifica si hay filas duplicadas específicamente en las columnas 'id_vivienda', 'id_hogar', 'id_persona'.

In [22]:
df_empleo.duplicated(subset=['id_vivienda', 'id_hogar', 'id_persona']).any()

np.False_

# Ejercicio 4: Valores faltantes

Los datos del mundo real raramente están completos. Aquí, trataremos los valores faltantes en la columna de ingresos.

1. Calcula el número de valores nulos (`NaN`) en la columna `ingreso_laboral` **antes** de cualquier modificación.

In [23]:
sum(df_empleo['ingreso_laboral'].isna())

231144

2. En la GEIH, un ingreso faltante a menudo significa que la persona no reportó ingresos o no aplica (ej. no trabaja). Una estrategia común es imputar estos valores con `0`. Rellena los valores `NaN` en la columna `ingreso_laboral` con `0`.

In [24]:
df_empleo['ingreso_laboral'] = df_empleo['ingreso_laboral'].fillna(0)

# Ejercicio 5: Decodificar variables

Las variables categóricas a menudo necesitan ser "traducidas" para hacerlas más entendibles para el análisis.

1. Usa los siguientes diccionarios para reemplazar los códigos numéricos por etiquetas de texto en las siguientes columnas: 'clase', 'sexo', 'grupo_etnico', 'nivel_educativo' y 'categoria_ocupacional'. Muestra los conteos de las nuevas categorías usando `.value_counts()` para verificar el cambio en cada una de las columnas.

In [25]:
dic_clase = {1: 'Cabeceras', 2: 'Centros poblados y rural disperso'}
dic_sexo = {1: 'Hombre', 2: 'Mujer'}
dic_etnico = {1: 'Indígena', 2: 'Gitano (Rom)', 3: 'Raizal del archipiélago', 4: 'Palenquero',
              5: 'Negro, mulato (afrodescendiente)', 6: 'Ninguno de los anteriores'}
dic_nivel_educativo = {1: 'Ninguno', 2: 'Educación media', 3: 'Educación media',
                       4: 'Educación media', 5: 'Técnica profesional', 6: 'Tecnológica',
                       7: 'Universitaria', 8: 'Especialización', 9: 'Maestría',
                       10: 'Doctorado', 99: 'No sabe, no informa'}
dic_cat_ocu = {1: 'Asalariado', 2: 'Asalariado', 3: 'Asalariado',
               8: 'Asalariado', 4: 'Independiente', 5: 'Independiente',
               9: 'Independiente', 6: 'Trabajador sin remuneración',
               7: 'Trabajador sin remuneración'}

In [ ]:
### TU CÓDIGO AQUÍ ###

In [ ]:
### TU CÓDIGO AQUÍ ###

In [ ]:
### TU CÓDIGO AQUÍ ###

In [ ]:
### TU CÓDIGO AQUÍ ###

In [ ]:
### TU CÓDIGO AQUÍ ###

# Ejercicio 6: Reorganizar columnas

1. Reorganiza las columnas con el siguiente orden: 'id_vivienda', 'id_hogar', 'id_persona', 'mes', 'clase', 'departamento', 'nombre_dpto',     'factor_expansion', 'poblacion_total', 'sexo', 'edad', 'grupo_etnico', 'nivel_educativo', 'ocupados', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu', 'ingreso_laboral'

In [ ]:
### TU CÓDIGO AQUÍ ###

# Ejercicio 7: Cambiar tipo de dato

Para realizar cálculos y análisis correctamente, las columnas deben tener el tipo de dato adecuado (numérico, categórico, etc.).

1.  Muestra en pantalla los tipos de datos actuales de `df_empleo`.

In [ ]:
### TU CÓDIGO AQUÍ ###

2.  Las siguientes columnas representan categorías: 'clase', 'departamento', 'nombre_dpto', 'sexo', 'grupo_etnico', 'nivel_educativo', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu'. Conviértelas al tipo `category` para optimizar el uso de memoria y facilitar análisis futuros.

In [ ]:
### TU CÓDIGO AQUÍ ###

# Ejercicio 8: Ordenar el dataframe (5%)

1. Ordena el dataframe por la columna "edad" de mayor a menor. Observa la columna 'edad' y escribe en una celda de markdown cuál fue la edad mínima y la edad máxima de las personas que respondieron la encuesta de la GEIH.

In [ ]:
### TU CÓDIGO AQUÍ ###

Escribe tu análisis aquí:

# Ejercicio 9: Groupby

Agrupar los datos por categorías, nos permite realizar análisis más profundos y obtener insights valiosos, que a simple vista no vemos en la base de datos.

1. Crea un nuevo dataframe llamado "df_sexo" donde se agrupe por 'sexo' y se calcule la suma de las columnas 'poblacion_total' y 'ocupados'. Crea una nueva columna que se llame 'porcentaje_ocupados' donde dividas las columna 'ocupados' sobre 'poblacion_total'. Al final usa reset_index() para convertir las categorías de sexo en una columna.

In [ ]:
### TU CÓDIGO AQUÍ ###

2. Crea un nuevo dataframe llamado "df_educacion" donde se agrupe por 'nivel_educativo' y se calcule la suma de las columnas 'poblacion_total' y 'ocupados'. Crea una nueva columna que se llame 'porcentaje_ocupados' donde dividas las columna 'ocupados' sobre 'poblacion_total'. Al final usa reset_index() para convertir las categorías de nivel educativo en una columna.

In [ ]:
### TU CÓDIGO AQUÍ ###

3. En una celda de Markdown escribe qué conclusiones puedes sacar de la información obtenida en df_sexo y df_educacion.

Escribe tu análisis aquí:

# Ejercicio 10: Filtrar datos

1. A partir de df_empleo, crea el DataFrame `df_ing` con observaciones donde `ingreso_laboral` no sea nulo y además sea mayor estrictamente al salario mínimo para 2026 (con subsidio de transporte).

In [ ]:
### TU CÓDIGO AQUÍ ###

2. ¿Cuántas personas tienen un salario estrictamente mayor al salario mínimo?

In [ ]:
### TU CÓDIGO AQUÍ ###

3. Crea el dataframe df_mujeres donde se encuentren solamente mujeres que están ubicadas en el departamento del Tolima, que son asalariadas y cuyo nivel educativo es educación media o superior.

In [ ]:
### TU CÓDIGO AQUÍ ###

4. ¿Cuáles son las dimensiones de df_mujeres?

In [ ]:
### TU CÓDIGO AQUÍ ###